services:
  solara-music:
    image: evecus/solara-music:latest 
    container_name: solara-music
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SOLARA_PASSWORD=solara123
      - SESSION_SECRET=KLmlKDruIBRYjrT5ct7B3xqG25ZF2p59
    volumes:
      - ./logs:/app/logs
